### ISSUE TITLE
[Request] generate json file for import from asyncapi / openapi specification

### ISSUE THREAD

**Issue by pavlikm** [firecamp-io/firecamp#200]
I have many big projects, with many endpoints. Some are webscockets, some are REST, and I can generate openapi / asyncapi documentation for them. Problemm is, when I cange something (changed payload, new endpoint), I need to update it in firecamp collection. It would be great, if this json can be generated automatically

**Comment by Nishchit14** [comment]
@pavlikm Here I can see a huge opportunity with this intelligence feature. but It'll come up with more complexity too. Should we discuss the one simple end-to-end use case here to get started? I really appreciate your contribution :)

**Comment by pavlikm** [comment]
@Nishchit14 just upload yml file in upload dialog, take examples from given openapi yml file (if provided, or generate custom payloads by properties types) and build collections with endpoints from this openapi. Possibly use URL to swagger in import dialog.
![image](https://user-images.githubusercontent.com/78898602/152746264-8e96fb62-002b-4d48-812e-db55e2362d3b.png)

You can inspire with postman where this feature works:
<img width="452" alt="postman-openpapi" src="https://user-images.githubusercontent.com/78898602/152746562-1191b27b-75c0-4e19-92ad-3f9ca8d89f24.png">

**Comment by Nishchit14** [comment]
I think this feature is already available in Firecamp @pavlikm. please review the below GIF.  You can import Firecamp, Postman, Insomnia, OpenAPI, AsyncAPI, and HAR format there. please try it and let me know your experience with it :), I am sure we need to improve it with higher DX.

![import-openapi-spec](https://user-images.githubusercontent.com/5078921/153339343-5b487bb8-bd5b-45c4-84a0-8ee434c9c90a.gif)

**Comment by pavlikm** [comment]
@Nishchit14 for swagger example petshop openapi it works perfectly. But for my openapi it creates only empty collection. Here is example openApi for test:

```yml
---
asyncapi: 2.1.0
info:
  title: test
  description: Some description for test api
  version: '1.0'
  contact: {}
servers:
  test:
    url: https://test.com/
    protocol: socket.io
    protocolVersion: '4'
    description: test description
    bindings: {}
components:
  schemas:
    getTestRequest:
      type: object
      properties:
        limit:
          type: number
    getTestResponse:
      type: object
      properties:
        status:
          type: boolean
defaultContentType: application/json
channels:
  getTest:
    publish:
      summary: request to getTest
      message:
        name: getTest
        payload:
          "$ref": "#/components/schemas/getTestRequest"
    subscribe:
      summary: response of test
      message:
        name: getTest
        payload:
          "$ref": "#/components/schemas/getTestResponse"

```
